/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteSsssArgs } from "./DeleteSsssArgs";
import { SsssCountArgs } from "./SsssCountArgs";
import { SsssFindManyArgs } from "./SsssFindManyArgs";
import { SsssFindUniqueArgs } from "./SsssFindUniqueArgs";
import { Ssss } from "./Ssss";
import { SsssService } from "../ssss.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Ssss)
export class SsssResolverBase {
  constructor(
    protected readonly service: SsssService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Ssss",
    action: "read",
    possession: "any",
  })
  async _ssssesMeta(
    @graphql.Args() args: SsssCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Ssss])
  @nestAccessControl.UseRoles({
    resource: "Ssss",
    action: "read",
    possession: "any",
  })
  async sssses(@graphql.Args() args: SsssFindManyArgs): Promise<Ssss[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Ssss, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Ssss",
    action: "read",
    possession: "own",
  })
  async ssss(@graphql.Args() args: SsssFindUniqueArgs): Promise<Ssss | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Ssss)
  @nestAccessControl.UseRoles({
    resource: "Ssss",
    action: "delete",
    possession: "any",
  })
  async deleteSsss(@graphql.Args() args: DeleteSsssArgs): Promise<Ssss | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
