/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteVvvArgs } from "./DeleteVvvArgs";
import { VvvCountArgs } from "./VvvCountArgs";
import { VvvFindManyArgs } from "./VvvFindManyArgs";
import { VvvFindUniqueArgs } from "./VvvFindUniqueArgs";
import { Vvv } from "./Vvv";
import { VvvService } from "../vvv.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Vvv)
export class VvvResolverBase {
  constructor(
    protected readonly service: VvvService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Vvv",
    action: "read",
    possession: "any",
  })
  async _vvvsMeta(
    @graphql.Args() args: VvvCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Vvv])
  @nestAccessControl.UseRoles({
    resource: "Vvv",
    action: "read",
    possession: "any",
  })
  async vvvs(@graphql.Args() args: VvvFindManyArgs): Promise<Vvv[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Vvv, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Vvv",
    action: "read",
    possession: "own",
  })
  async vvv(@graphql.Args() args: VvvFindUniqueArgs): Promise<Vvv | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Vvv)
  @nestAccessControl.UseRoles({
    resource: "Vvv",
    action: "delete",
    possession: "any",
  })
  async deleteVvv(@graphql.Args() args: DeleteVvvArgs): Promise<Vvv | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
